### PR TITLE
total mob limit

### PR DESCRIPTION
**Pull request by felzix**
Mob limit equals maxmob - pmuli \* [number of players].

plugin jar: http://www.mediafire.com/?6110b2z2dbd6c98

### CODE REVIEW

**Comment by ttk2** [comment]
I was going to give this a go on the next long term Civtest round along with whatever enchanting/beacon changes we end up making. I don't want to rush anything like this into production for reasons of the trouble changes like this have caused in the past.

**Comment by Celdecea** [comment]
Hello, thank you for your commit. Tonight I'm spending lots of time on MusterCull so I can take a further look in a few hours.

There is only one big thing I can see. From the damage laborer you call your getMobs each time it runs and looking [here](https://github.com/Celdecea/MusterCull/pull/8/files#L4R30) I see that if the same check fails we call getMobs() again, and again every time we spawn. When the server is its busiest it will be doing quite a bit of extra cpu work, and burying getMobs() in overHardLimit() makes me question whether even Hotspot would be able to cache that, particularly with the branch which has been predicting false up until a mob spike and is now playing heart monitor.

The plugin exists to solve a performance issue so we have to try not to introduce any of our own. I think if you want to get your mob count using this getMobs() method I would ask that you set up another laborer task for a configurable length of time and save the results somewhere. You can also use an incrementer in the mob spawn event as well and in damage laborer compare two integers rather than all that big O.

You followed the code path very well and so far everything else looks good to me. I'm anxious to see this get in so if you have questions on putting up another laborer let me know, but I suspect you know what you are doing.

**Comment by felzix** [comment]
"There is only one big thing I can see. From the damage laborer you call
your getMobs each time it runs and looking
herehttps://github.com/Celdecea/MusterCull/pull/8/files#L4R30 I
see that if the same check fails we call getMobs() again, and again every
time we spawn. When the server is its busiest it will be doing quite a bit
of extra cpu work, and burying getMobs() in overHardLimit() makes me
question whether even Hotspot would be able to cache that, particularly
with the branch which has been predicting false up until a mob spike and is
now playing heart monitor."

Good point. I think I can keep the same basic structure by splitting up
getMobs for its different purposes. For the mob count it doesn't matter if
players are included since that's just subtraction with constant time
operations. And a list of mobs is only needed when killing mobs rather than
preventing their spawning. I'm not sure if I actually need to test if mobs
are dead so whether or not this plan works will bear out in my testing.

I don't know if the mob lists and the player list are synchronized so to
avoid a possible infinite loop, I'll add a kill buffer. When damageLaborer
runs, it will try to kill down to the mob cap minus the player count. I
considered doing this anyway so that spawning wouldn't completely stop,
it'd just become extremely slow.

"You can also use an incrementer in the mob spawn event as well and in
damage laborer compare two integers rather than all that big O."

Mobs created when a previously-generated chunk is loaded don't
trigger onCreatureSpawn. I don't know why. I might be able to grab onto the
chunk loading or populating events though.

"I'm anxious to see this get in so if you have questions on putting up
another laborer let me know, but I suspect you know what you are doing."

I've never actually worked with multithreading outside of servers talking
through sockets. I don't think I need to add a new laborer (though the
class hierarchy makes me want to add one!) but I will ask you about it if I
do.

I'll probably submit a new patch around Thursday morning.

Thanks,

Robert Davidson

**Comment by felzix** [comment]
I added some changes. It still runs at O(N) but does so far fewer times.

1) I created getMobCount that runs in constant time (with respect to entities) which gets called unless there are too many mobs.
2) I moved the killing code to its own laborer that is by default set with a large enough tick count (with ~50% safety buffer) that my home server that getMobs only gets called once when there are more mobs than the cap allows. If players are constantly loading up old chunks with mobs then getMobs will be run repeatedly.

But the admin can set hard_cap_between_ticks high enough that the purges happen seldom enough to not be any more drain on resources than the extra mobs are.

updated bukkit plugin jar: http://www.mediafire.com/?aqyzqym9nuyxe2d

**Comment by ttk2** [comment]
cool, I will be excited to test this after Zab reviews the code.

**Comment by Celdecea** [comment]
This looks good. I'm willing to let hotspot have a shot at optimizing it now since it will be clear if there are any issues under heavy load.

You'll have to merge and rebase the current repo to your own and add to your commit if I am to be able to merge it.

**Comment by Celdecea** [comment]
Bump. Felzix: I can't merge this commit without your action first.

**Comment by felzix** [comment]
What action?

**Comment by Celdecea** [comment]
Below our messages it says "This pull request cannot be automatically merged."

You have to fetch the updates from the current repository, merge, then add them to your commit. It should update the pull request automatically.

**Comment by Celdecea** [comment]
Your plugin is running on the CivCraft test server and ttk2 has a copy of the jar. You may want to message him with your suggestions about updates to config.yml.

Good luck!

**Pull request merged**
